### ISSUE TITLE
Refactor main class so that all info, warning and error messages are accessible by caller

### ISSUE THREAD

**Issue by agstephens** [cedadev/cf-checker#7]
# Overview

The CFChecker class prints all its messages when they occur and records counts of errors (self.err) and warnings (self.warn).

We want to refactor the code so that:

1. All info, warning and error messages are also available to the calling after running the checker.
2. By default, the checker still prints out all the messages as they occur.
3. Optionally, you can switch off the messages so that they are not displayed.
  * or possibly, if easy to implement, the user could specify the log-level that should be printed.

Please develop this solution in a branch so that we can test fully with a number of test files before we decide to merge with the master.
  
# Implementation

I suggest implementing with a global "self.checks" attribute that has the following structure:

    {"global": {"INFO": [], "WARN": [], "ERROR": []},
	 "variables": OrderedDict({
		"<var1>": 
			{"INFO": [], "WARN": [], "ERROR": []},
		"<var2>": 
			{"INFO": [], "WARN": [], "ERROR": []},
		})
	}
	
You would need to have a method to count the INFO, WARN and ERROR messages at the end so that the checker can report these numbers as it normally does (see example output below).

# Note on Installing and running

    $ mkdir tmp
    $ cd tmp
    $ git clone https://github.com/cedadev/cf-checker
    $ virtualenv-2.7 --system-site-packages venv
    $ . venv/bin/activate
    $ cd cf-checker/
    $ pip install setup.py
    $ cfchecks /badc/cmip5/data/cmip5/output1/MOHC/HadGEM2-ES/rcp45/day/land/day/r1i1p1/latest/mrsos/mrsos_day_HadGEM2-ES_rcp45_r1i1p1_20151201-20251130.nc

The output should look like:

	CHECKING NetCDF FILE: /badc/cmip5/data/cmip5/output1/MOHC/HadGEM2-ES/rcp45/day/land/day/r1i1p1/latest/mrsos/mrsos_day_HadGEM2-ES_rcp45_r1i1p1_20151201-20251130.nc
	=====================
	Using CF Checker Version 2.0.9
	Checking against CF Version CF-1.6
	Using Standard Name Table Version 29 (2015-07-08T09:43:36Z)
	Using Area Type Table Version 3 (8 July 2015)

	WARNING: Inconsistency - This netCDF file appears to contain CF-1.4 data, but you've requested a validity check against CF-1.6

	------------------
	Checking variable: time_bnds
	------------------

	------------------
	Checking variable: lat_bnds
	------------------

	------------------
	Checking variable: depth_bnds
	------------------

	------------------
	Checking variable: lon
	------------------

	------------------
	Checking variable: lon_bnds
	------------------

	------------------
	Checking variable: depth
	------------------

	------------------
	Checking variable: time
	------------------

	------------------
	Checking variable: lat
	------------------

	------------------
	Checking variable: mrsos
	------------------
	INFO: attribute 'history' is being used in a non-standard way
	WARNING (7.2): cell_measures referring to variable 'areacella' that doesn't exist in this netCDF file.
	INFO (7.2): This is strictly an error if the cell_measures variable is not included in the dataset.

	ERRORS detected: 0
	WARNINGS given: 2
	INFORMATION messages: 1

**Comment by alaniwi** [comment]
Checking against 1.4 gives 1 error and 1 warning, which is handy.

{{{
cfchecks -v 1.4 mrsos_day_HadGEM2-ES_rcp45_r1i1p1_20151201-20251130.nc

CHECKING NetCDF FILE: mrsos_day_HadGEM2-ES_rcp45_r1i1p1_20151201-20251130.nc
=====================
Using CF Checker Version 2.0.9
Checking against CF Version CF-1.4
Using Standard Name Table Version 29 (2015-07-08T09:43:36Z)
Using Area Type Table Version 3 (8 July 2015)


------------------
Checking variable: time_bnds
------------------

------------------
Checking variable: lat_bnds
------------------

------------------
Checking variable: depth_bnds
------------------

------------------
Checking variable: lon
------------------

------------------
Checking variable: lon_bnds
------------------

------------------
Checking variable: depth
------------------
ERROR (4): Axis attribute is not allowed for auxillary coordinate variables.

------------------
Checking variable: time
------------------

------------------
Checking variable: lat
------------------

------------------
Checking variable: mrsos
------------------
INFO: attribute 'history' is being used in a non-standard way
WARNING (7.2): cell_measures referring to variable 'areacella' that doesn't exist in this netCDF file.
INFO (7.2): This is strictly an error if the cell_measures variable is not included in the dataset.

ERRORS detected: 1
WARNINGS given: 1
INFORMATION messages: 1
}}}

**Comment by alaniwi** [comment]
To simplify one aspect of the code, I am removing return values from many functions where the only purpose of the return code was to indicate whether an errors were reported by the function.  The return codes were not actually used (other than to set `rc` in the calling code in `_checker`, which was itself never used).  If it later becomes desirable to test whether any particular check logs any new errors, this could easily be done via a generic wrapper that obtains the error counts before and after the call, and returns a value accordingly.

**Comment by alaniwi** [comment]
This is now believed to be done and working, though it is in branch ai_dev, and I will leave you to merge it into master. (Note: there were two commits, and it will probably be clearer to look at the combined effect of the commits rather than each individually.)

Overall effect of the changes are:
* I have added a dictionary called `all_results` to the `CFChecker` instance.  This contains an ordered dictionary of files in the order checked, with key = filename and value = one of the dictionaries that you specified.  This is in place of self.checks, and reflects the fact that the instance may be used to check more than one file.
* I have also added a list of strings called `all_messages`, which contains the messages in the order that they were printed, rather than sorted into the structure discussed above.
* I have added the following arguments to `__init__`:
 * `debug` - if `debug=True` passed, then certain messages added with `self._add_debug()` are printed; otherwise they are ignored. Also in the main program, it gets set if command line arg `-d` is used.
 * `silent` - if `silent=True` passed, then no messages are output; what would have been printed can be recovered from the `all_messages` list.

A caveat is that there were a *lot* of lines to change where messages are printed, and if a bug (other than a syntax error) was introduced then this might only be exposed by testing it with cases where these lines are actually executed, so please throw lots of test cases at it.

(I have refrained from any other refactoring - although note earlier comment re method return values - but some things worth addressing are: use of whitespace, including indentation levels, and the use of "yes" and "no" as boolean values.)

**Comment by RosalynHatcher** [comment]
Fixed printed output so that it is formatted as it was originally.  Fixes to a couple of the output messages.

Merged 7416ed25bfbdc31f5e98dc4ad671b9b0ee332e17 onto master.

**Comment by alaniwi** [comment]
Closing. Please reopen adding appropriate description if you think there is anything still needing doing.
